# Setup
title:               Martin
tagline:             'Growth, Lets live today which is better than yesterday'
description:         '<a strong><font size="5">Martin</font></a>'
url:                 https://ssaru.github.io/
baseurl:             ''
paginate:            5
paginate_path:       '/blog/page:num'

gem:                 [jekyll-paginate]

# About/contact
author:
  name:              Martin
  email:             dhhwang89@gmail.com
  url:               https://ssaru.github.io/

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/ssaru

disqus:
  shortname:         martin
