# Setup
title:               Jim
tagline:             'in the Box'
description:         'The blog of Jimmy/Jim from Lubycon'
url:                 https://jimheo.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jim
  email:             gjwlals111@gmail.com

# Custom vars
version:             1.0.0
