# Setup
title:               The blog
tagline:             'of Jimmy/Jim from Lubycon'
description:         '<a strong><font size="5">JimintheBox</font></a>'
url:                 https://jimheo.github.io/
baseurl:             ''
paginate:            5
paginate_path:       '/blog/page:num'

gem:                 [jekyll-paginate]

# About/contact
author:
  name:              Jim
  email:             gjwlals111@gmail.com
  url:               https://jimheo.github.io/
  gravatar:          https://ko.gravatar.com/gjwlals111565003472
  photo:             https://secure.gravatar.com/avatar/11c650c5a808a5ce1a7ad1c1c9bdb4cd

# Custom vars
version:             1.0.0

github:
  repo:              https://github.com/jimheo