# Setup
title:               The blog
tagline:             'of Jimmy/Jim from Lubycon'
description:         'JimintheBox'
url:                 https://jimheo.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jim
  email:             gjwlals111@gmail.com

# Custom vars
version:             1.0.0
